apiVersion: v1
kind: Service
metadata:
  name: login-svc
  labels:
    app: login-adam
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-adam
